import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export type Route = {
  title: string;
  href: string;
  description: string;
};

const routes: Route[] = [
  {
    title: "Home",
    href: "/",
    description: "Go back to the homepage.",
  },
  {
    title: "About Us",
    href: "/about-us",
    description: "Learn more about us and our mission.",
  },
  {
    title: "FAQ",
    href: "/faq",
    description: "Find answers to frequently asked questions.",
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <NavBar routes={routes} />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
